name: CI/CD Pipeline (Workaround para EC2)

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    name: Deploy a EC2 (Build y Run)
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Configurar llave SSH para EC2
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Solo escaneamos el host de EC2
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: 2. Desplegar en EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          
          REPO_URL: "https://github.com/${{ github.repository }}.git" 
          REPO_NAME: ${{ github.event.repository.name }}
          
          APP_FLASK_ENV: prod
          APP_TABLE_NAME: perros_prod
          APP_AWS_REGION: ${{ secrets.AWS_REGION }}
        
        run: |
          echo "Conectando a $USER@$HOST"
          ssh -i ~/.ssh/id_rsa $USER@$HOST << EOF
            
            # 1. Instalar Git (si no está)
            sudo dnf install git -y
            
            # 2. Clonar o actualizar el repositorio
            if [ -d "$REPO_NAME" ] ; then
              echo "Actualizando repositorio..."
              cd $REPO_NAME
              git pull
            else
              echo "Clonando repositorio..."
              git clone $REPO_URL
              cd $REPO_NAME
            fi
            
            echo "En el directorio $(pwd)"

            # 3. Construir la imagen Docker localmente (Actividad 3 y 4 combinadas)
            echo "Construyendo imagen local..."
            docker build -t mi-app-crud:latest .
            
            # 4. Detener y eliminar el contenedor anterior (Actividad 5)
            echo "Deteniendo contenedor anterior..."
            docker stop mi-app-crud || true
            docker rm mi-app-crud || true
            
            # 5. Ejecutar el nuevo contenedor (usando la imagen local)
            echo "Ejecutando nuevo contenedor..."
            docker run -d --name mi-app-crud \
              -p 80:5000 \
              -e FLASK_ENV=$APP_FLASK_ENV \
              -e DYNAMODB_TABLE=$APP_TABLE_NAME \
              -e AWS_REGION=$APP_AWS_REGION \
              mi-app-crud:latest
              
            echo "Despliegue completado."
            
            # 6. Limpiar imágenes viejas
            docker image prune -f
          EOF